version: "3.8"
services:
  mongo:
    image: mongo:4.4
    container_name: Jmalcloud_DB
    restart: unless-stopped
    networks:
      - unet
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ${JMC_DB}:/data/db:rw
    command: --wiredTigerCacheSizeGB 0.5
    labels:
      - net.unraid.docker.icon=${icon}
  office:
    container_name: Jmalcloud_Office
    image: onlyoffice/documentserver:7.0.0.132
    restart: unless-stopped
    networks:
      - unet
    environment:
      - TZ=Asia/Shanghai
    labels:
      - net.unraid.docker.icon=${icon}
  drawio-webapp:
    container_name: Jmalcloud_Drawio
    image: jgraph/drawio:20.2.3
    restart: unless-stopped
    networks:
      - unet
    environment:
      - TZ=Asia/Shanghai
    labels:
      - net.unraid.docker.icon=${icon}
  jmalcloud:
    image: jmal/jmalcloud:latest
    container_name: Jmalcloud_Server
    restart: unless-stopped
    ports:
      - 7072:8088
    networks:
      - unet
    environment:
      - PUID=1000
      - PGID=100
      - MONGODB_URI=mongodb://mongo:27017/jmalcloud
      - TZ=Asia/Shanghai
    volumes:
      - ${JMC_DATA}:/jmalcloud/files:rw
    labels:
      - net.unraid.docker.icon=${icon}
    depends_on:
      mongo:
        condition: service_started
  nginx:
    container_name: Jmalcloud_Nginx
    image: jmal/jmalcloud-nginx:latest
    restart: unless-stopped
    ports:
      - 7070:80 # 界面访问端口
      - 7071:8089 # 博客端口
    networks:
      - unet
    environment:
      - TZ=Asia/Shanghai
    labels:
      - net.unraid.docker.webui=${webui}
      - net.unraid.docker.icon=${icon}
    depends_on:
      jmalcloud:
        condition: service_started
      office:
        condition: service_started
      drawio-webapp:
        condition: service_started
networks:
  unet:
    driver: bridge
    attachable: true
    external: true
